### ISSUE TITLE
Website Templates/Similar Sites

### ISSUE THREAD

**Issue by j-dogcoder** [Heptagram-Bot/heptagram.xyz#1]
- [https://www.thedigitalpanda.com](https://www.thedigitalpanda.com)
- [http://veille.reputationsquad.com/#des-solutions-concretes](http://veille.reputationsquad.com/#des-solutions-concretes)
--------------------------
- https://dribbble.com/shots/14312609-Future-Landing-Page-UI
- https://dribbble.com/shots/15384019-Dance-of-the-Moon-Interface-Concept
- https://dribbble.com/shots/5855757-New-Product-Page-Design-for-Global-Telecommunications-Platform
- https://dribbble.com/shots/13965336-Robust-Intelligence-Website-Update-Case-Study-Videos

**Comment by MidouWebDev** [comment]
#4

**Comment by MidouWebDev** [comment]
@j-dogcoder i think we should close this issue ?
