### ISSUE TITLE
🐛 [BUG] The Website Link in the about section

### ISSUE THREAD

**Issue by MidouWebDev** [Heptagram-Bot/heptagram.xyz#20]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Here is what we have as the website link 

![image](https://user-images.githubusercontent.com/72341453/128524360-6bce5cec-d83b-4c0b-a320-7e758b607f4b.png)

### Expected Behavior

I expected to see : https://heptagram.xyz 

### Steps To Reproduce

1. go to https://github.com/Heptagram-Bot/heptagram.xyz
2. go to "about" section
3. check the link and see error

**Comment by MidouWebDev** [comment]
@j-dogcoder can you look into that ?

**Comment by j-dogcoder** [comment]
Fixed!
