### ISSUE TITLE
✨❓ Feature Request: Add myself to the list of Heptagram developers

### ISSUE THREAD

**Issue by Panquesito7** [Heptagram-Bot/heptagram.xyz#44]
**Description**

I am part of the Heptagram development. I am a website maintainer and bot maintainer.
I would like to be added to the Heptagram team on the website as shown [**here**](https://heptagram.xyz/heptagram-devs.html). 🙂

Thank you.

**Comment by j-dogcoder** [comment]
@MidouWebDev

**Comment by MidouWebDev** [comment]
@Panquesito7 i worked on the whole website solo, and you're considering yourself website maintainer ?!!

**Comment by j-dogcoder** [comment]
> @Panquesito7 i worked on the whole website solo, and you're considering yourself website maintainer ?!!

As I said in a DM to @MidouWebDev, Yes, I consider @Panquesito7 to be a part of the website team.

**Comment by MidouWebDev** [comment]
@j-dogcoder yess
@Panquesito7 is part of the website team and i am the website maintainer 😉

**Comment by Panquesito7** [comment]
Oh, I'm sorry for that! I didn't want to say that 😅  I just consider myself a maintainer of the website. That doesn't mean I'm saying I made the website. 🙂

**Comment by Panquesito7** [comment]
Closing this issue as it's already solved. Thanks. 🙂
