### ISSUE TITLE
❓ Switching to React.js : To Do

### ISSUE THREAD

**Issue by MidouWebDev** [Heptagram-Bot/heptagram.xyz#53]
## Description

So that users can customise the commands, features...
We should re-write the website to REACTJS to code the dashboard !

## Main Tasks : 

- [x] #62
- [x] #64 
- [x] #65 
- [x] #66 
- [x] #68
- [x] #70 
- [x] #73 
- [ ] #78 
- [ ] #79

**Comment by anubhav06** [comment]
Hi, is this staff only or I can contribute as well ?
I am a beginner in ReactJS though, and I could try and do any of the small task you wish to assign me (if it's open to contribution)

**Comment by MidouWebDev** [comment]
@j-dogcoder Here is the Lighthouse Report of the React Version of the Website
We should just improve the performance sooner !

![image](https://user-images.githubusercontent.com/72341453/139598691-030df131-f3c1-40bb-b5d3-c2d5b4a94b75.png)

**Comment by j-dogcoder** [comment]
👍🏻 Thanks!
