### ISSUE TITLE
🐛 [BUG] Define the homepage.js as the home page of the react website

### ISSUE THREAD

**Issue by MidouWebDev** [Heptagram-Bot/heptagram.xyz#64]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Home Page not defined

### Expected Behavior

Once we run npm start we should see the /home page directly

### Steps To Reproduce

1. Run npm start
2. see preview : localhost:3000
3. see error (no content, no home page)
4. add /home to see the home page

### Anything else?

@Panquesito7

**Comment by MidouWebDev** [comment]
@Panquesito7 once we run npm start we see localhost:3000 and we need to add /home to see the home page.
Is there a way to see directly the homepage ?

**Comment by Panquesito7** [comment]
> @Panquesito7 once we run npm start we see localhost:3000 and we need to add /home to see the home page. Is there a way to see directly the homepage ?

Like on a link? I'm not sure if that's possible unless we add it on GitHub Pages or another hosting provider. 😅
