### ISSUE TITLE
🐛 [BUG] Hamburger Menu not working in the REACT.JS website version

### ISSUE THREAD

**Issue by MidouWebDev** [Heptagram-Bot/heptagram.xyz#65]
### If you're interested, ping me please to assign you and give you more infos.

**Comment by MidouWebDev** [comment]
@Panquesito7 we need your help please 🙏🏼 
Thanks, brother.

**Comment by Panquesito7** [comment]
I tried running the website in Gitpod to see how it looks and what can I do, but it didn't work. Any ideas on how to run it? 🤔

**Comment by MidouWebDev** [comment]
@Panquesito7 you can't clone, npm install, npm start then edit some code and see preview ?

**Comment by Panquesito7** [comment]
> @Panquesito7 you can't clone, npm install, npm start then edit some code and see preview ?

I tried in Gitpod, but it didn't work.

**Comment by MidouWebDev** [comment]
@Panquesito7 we didn't add the script to the react website that's why it isn't working.
You can find the js script for the hamburger menu in https://github.com/Heptagram-Bot/heptagram.xyz in the js folder : main.js
