### ISSUE TITLE
🐛 [BUG] Redirect to 404

### ISSUE THREAD

**Issue by MidouWebDev** [Heptagram-Bot/heptagram.xyz#94]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Once the user types a wrong link, he should be redirected to the error 404 page.

**Comment by Kevan-Y** [comment]
Hi, can I work on this issue to me? Thanks

**Comment by MidouWebDev** [comment]
Sure @Kevan-Y 
Thank you so much !
