### ISSUE TITLE
✨❓ Feature Request: Add Prettier config

### ISSUE THREAD

**Issue by Kevan-Y** [Heptagram-Bot/heptagram.xyz#98]
@MidouWebDev 
**Description**
Add prettier config file. So everyone working will keep the same style. 

Optional - Can also add a husky pre-commit, to check if the style is correct on commit

**Comment by MidouWebDev** [comment]
Yeah good idea @Kevan-Y to add the prettier config file

**Comment by MidouWebDev** [comment]
For adding Husky, let's ask @j-dogcoder

**Comment by j-dogcoder** [comment]
Fine to add the file, but not husky please

**Comment by MidouWebDev** [comment]
@Kevan-Y
